### ISSUE TITLE
Issue while building the quadratic project.

### ISSUE THREAD

**Issue by imrishabh18** [second-state/wasm-learning#3]
I am using docker to build the quadratic project and getting this error. Need help to resolve this error.
**use of undeclared type or module `serde_json`**
![Screenshot from 2020-08-02 21-59-46](https://user-images.githubusercontent.com/38923768/89127542-d568e780-d50b-11ea-8fcd-fdaebb76a9df.png)

**Comment by juntao** [comment]
You are using the SSVM-nodejs-starter project but changed src/lib.rs to use serde. You need to change Cargo.toml to declare serde as a dependency as well.
